from traveling_ethiopia import TravelingEthiopia
from astar_search import AStarSearch

connections = {
    "Addis Ababa": [("Adama", 3), ("Ambo", 5), ("Debre Berhan", 5), ("Debre Markos", 13)],
    "Adama": [("Matahara", 3), ("Asella", 4), ("Batu", 4), ("Addis Ababa", 3)],
    "Ambo": [("Wolkite", 6), ("Addis Ababa", 5), ("Nekemte", 8)],
    "Debre Berhan": [("Addis Ababa", 5), ("Debre Sina", 2)],
    "Debre Markos": [("Addis Ababa", 13), ("Debre Sina", 17), ("Finote Selam", 3)],
    "Matahara": [("Adama", 3), ("Awash", 1)],
    "Asella": [("Adama", 4), ("Assasa", 4)],
    "Batu": [("Adama", 4), ("Buta Jirra", 2), ("Shashamene", 3)],
    "Wolkite": [("Ambo", 6), ("Worabe", 5), ("Jimma", 8), ("Hossana", 5), ("Buta Jirra", 4)],
    "Nekemte": [("Ambo", 8), ("Bedelle", 4), ("Gimbi", 4)],
    "Debre Sina": [("Debre Berhan", 2), ("Kemise", 7), ("Debre Markos", 17)],
    "Finote Selam": [("Debre Markos", 3), ("Bahirdar", 6), ("Injibara", 2)],
    "Awash": [("Chiro", 4), ("Gobi Rasu", 5), ("Matahara", 1)],
    "Assasa": [("Asella", 4), ("Dodolla", 1)],
    "Buta Jirra": [("Batu", 2), ("Wolkite", 4), ("Worabe", 2)],
    "Shashamene": [("Batu", 3), ("Dodolla", 3), ("Hawassa", 1), ("Hossana", 7), ("Worabe", 6)],
    "Worabe": [("Wolkite", 5), ("Hossana", 2), ("Shashamene", 6), ("Buta Jirra", 2)],
    "Jimma": [("Wolkite", 8), ("Bonga", 4), ("Bedelle", 7)],
    "Hossana": [("Shashamene", 7), ("Worabe", 2), ("Wolkite", 5), ("Wolaita Sodo", 4)],
    "Bedelle": [("Nekemte", 4), ("Gore", 6), ("Jimma", 7)],
    "Gimbi": [("Nekemte", 4), ("Dambidollo", 6), ("Assosa", 8)],
    "Kemise": [("Debre Sina", 7), ("Dessie", 4)],
    "Bahirdar": [("Finote Selam", 6), ("Injibara", 4), ("Metekel", 11), ("Azezo", 7), ("Debre Tabor", 4)],
    "Injibara": [("Bahirdar", 4), ("Finote Selam", 2)],
    "Chiro": [("Awash", 4), ("Dire Dawa", 8)],
    "Gobi Rasu": [("Awash", 5), ("Samara", 10)],
    "Dodolla": [("Assasa", 1), ("Shashamene", 3), ("Robe", 13)],
    "Hawassa": [("Shashamene", 1), ("Dilla", 3)],
    "Bonga": [("Jimma", 4), ("Dawro", 10), ("Tepi", 8), ("Mizan Teferi", 4)],
    "Wolaita Sodo": [("Arba Minchi", 4), ("Dawro", 6), ("Hossana", 4)],
    "Gore": [("Tepi", 9), ("Gambella", 5), ("Bedelle", 6)],
    "Dambidollo": [("Gimbi", 6), ("Assosa", 12), ("Gambella", 4)],
    "Assosa": [("Gimbi", 8), ("Dambidollo", 12)],
    "Dessie": [("Kemise", 4), ("Woldia", 6)],
    "Metekel": [("Bahirdar", 11)],
    "Azezo": [("Gondar", 1), ("Bahirdar", 7), ("Metema", 7)],
    "Debre Tabor": [("Lalibella", 8), ("Gondar", 6), ("Bahirdar", 4)],
    "Dire Dawa": [("Chiro", 8), ("Harar", 4)],
    "Samara": [("Gobi Rasu", 10), ("Fanti Rasu", 7), ("Alamata", 11), ("Woldia", 8)],
    "Robe": [("Liben", 11), ("Dodolla", 13), ("Goba", 18), ("Sof Oumer", 23)],
    "Dilla": [("Hawassa", 3), ("Bulehora", 4)],
    "Dawro": [("Bonga", 10), ("Wolaita Sodo", 6)],
    "Tepi": [("Gore", 9), ("Bonga", 8), ("Mizan Teferi", 4)],
    "Mizan Teferi": [("Tepi", 4), ("Bonga", 4)],
    "Gambella": [("Gore", 5), ("Dambidollo", 4)],
    "Arba Minchi": [("Wolaita Sodo", 4)],
    "Harar": [("Dire Dawa", 4)],
    "Fanti Rasu": [("Samara", 7)],
    "Woldia": [("Dessie", 6), ("Lalibella", 12), ("Samara", 8)],
    "Lalibella": [("Debre Tabor", 8), ("Woldia", 12)],
    "Gondar": [("Azezo", 1), ("Metema", 10), ("Debre Tabor", 6)],
    "Metema": [("Azezo", 7), ("Gondar", 10)],
    "Alamata": [("Mekelle", 5), ("Samara", 11)],
    "Mekelle": [("Alamata", 5)],
    "Sof Oumer": [("Robe", 23)],
    "Liben": [("Robe", 11)],
    "Moyale": []
}

heuristics = {
    "Addis Ababa": 26,
    "Adama": 23,
    "Ambo": 27,
    "Debre Berhan": 30,
    "Debre Markos": 35,
    "Matahara": 21,
    "Asella": 27,
    "Batu": 25,
    "Wolkite": 26,
    "Nekemte": 35,
    "Debre Sina": 35,
    "Finote Selam": 37,
    "Awash": 20,
    "Assasa": 30,
    "Buta Jirra": 25,
    "Shashamene": 29,
    "Worabe": 28,
    "Jimma": 32,
    "Hossana": 28,
    "Bedelle": 38,
    "Gimbi": 40,
    "Kemise": 39,
    "Bahirdar": 41,
    "Injibara": 38,
    "Chiro": 30,
    "Gobi Rasu": 25,
    "Dodolla": 34,
    "Hawassa": 30,
    "Bonga": 36,
    "Wolaita Sodo": 33,
    "Gore": 40,
    "Dambidollo": 44,
    "Assosa": 50,
    "Dessie": 45,
    "Metekel": 50,
    "Azezo": 45,
    "Debre Tabor": 44,
    "Dire Dawa": 35,
    "Samara": 30,
    "Robe": 45,
    "Dilla": 34,
    "Dawro": 39,
    "Tepi": 40,
    "Mizan Teferi": 39,
    "Gambella": 50,
    "Arba Minchi": 37,
    "Harar": 38,
    "Fanti Rasu": 35,
    "Woldia": 42,
    "Lalibella": 50,
    "Gondar": 48,
    "Metema": 57,
    "Alamata": 45,
    "Mekelle": 50,
    "Sof Oumer": 55,
    "Liben": 48,
    "Moyale": 0
}

def main():
    traveling_ethiopia = TravelingEthiopia(AStarSearch, connections, heuristics)
    
    start_city = "Addis Ababa"
    goal_city = "Moyale"
    path, cost = traveling_ethiopia.find_path(start_city, goal_city)

    print(f"Path from {start_city} to {goal_city}: {path}")
    print(f"Total cost: {cost}")

if __name__ == "__main__":
    main()
